pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git credentialsId: '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', 
                url: 'https://github.com/Karunakar-Gyara/Jenkins-Zero-To-Hero.git',
                branch: 'main'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Buid Docker Image'
                    cd python-jenkins-argocd-k8s
                    docker build -t karunakargyara/django3:${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    docker login -u karunakargyara -p Goal@2023
                    docker push karunakargyara/django3:${BUILD_NUMBER}
                    '''
                }
            }
        }
        
        stage('Checkout K8S manifest SCM'){
            steps {
                git credentialsId: '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', 
                url: 'https://github.com/Karunakar-Gyara/Jenkins-Zero-To-Hero.git',
                branch: 'main'
            }
        }
        
        stage('Update K8S manifest & push to Repo'){
            steps {
                script{
                     withCredentials([usernamePassword(credentialsId: 'git123', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]){
                    
                    sh '''
                        cd python-jenkins-argocd-k8s/deploy
                        cat deploy.yaml
                        sed -i "s/$((${BUILD_NUMBER}-1))/${BUILD_NUMBER}/g" deploy.yaml
                        cat deploy.yaml
                        git add deploy.yaml
                        git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
                        git remote -v
                        git config --global user.name "Karunakar-Gyara"
                        git config --global user.email "karunakargyara74@gmail.com"
                        git push https://${GIT_PASSWORD}@github.com/Karunakar-Gyara/Jenkins-Zero-To-Hero.git
                     
                        ''' 
                     }
                
                }
            }
         }
        stage('Deploy app to GKE'){
            steps {
                script{
                    sh '''
                      cd python-jenkins-argocd-k8s
                      gcloud auth activate-service-account --key-file=gke.json
                      
                      cd python-jenkins-argocd-k8s/deploy
                      gcloud config set project mygkeproject-377409
                      gcloud container clusters get-credentials hello-gke --region us-west4
                      kubectl apply -f deploy.yaml
                      kubectl apply -f service.yaml
                      kubectl get pods-o wide
                     '''
               }
            }
        }
                     
        
    }
}
