pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git credentialsId: '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', 
                url: 'https://github.com/Karunakar-Gyara/Jenkins-Zero-To-Hero.git',
                branch: 'main'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Buid Docker Image'
                    cd python-jenkins-argocd-k8s
                    docker build -t karunakargyara/django2:${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    docker login -u karunakargyara -p Goal@2023
                    docker push karunakargyara/django2:${BUILD_NUMBER}
                    '''
                }
            }
        }
        
        stage('Checkout K8S manifest SCM'){
            steps {
                git credentialsId: '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', 
                url: 'https://github.com/Karunakar-Gyara/Jenkins-Zero-To-Hero.git',
                branch: 'main'
            }
        }
        
        stage('Update K8S manifest & push to Repo'){
            steps {
                script{
                     withCredentials([usernamePassword(credentialsId: 'git', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]){
                    
                    sh '''
                        cd python-jenkins-argocd-k8s/deploy
                        cat deploy.yaml
                        sed -i "s/8/${BUILD_NUMBER}/g" deploy.yaml
                        cat deploy.yaml
                        git add deploy.yaml
                        git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
                        git remote -v
                       
                        git push https://github.com/Karunakar-Gyara/Jenkins-Zero-To-Hero.git
                     
                        ''' 
                     }
                
                }
            }
        }
    }
}
