apiVersion: apps/v2
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: todo
        image: karunakargyara/django4:2
        ports:
        - containerPort: 8000
